"""add column status to projects

Revision ID: dd08f747f8d0
Revises: 1b0c1366b753
Create Date: 2025-02-13 11:40:06.994022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd08f747f8d0'
down_revision: Union[str, None] = '1b0c1366b753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects",sa.Column("status",sa.Boolean,default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "status")
    # ### end Alembic commands ###
